config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root to: "drugs#index"

  resources :drugs do
    resources :batches
  end

  resources :sgtins, only: %i(destroy create)

  mount Sidekiq::Web => 'sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :drug
  has_many :sgtin, dependent: :destroy
  has_many :batch_firms, dependent: :destroy
  has_many :firms, through: :batch_firms

  def formatted_expiration_date
    expiration_date.strftime('%d.%m.%Y')
  end

  scope :drug_owner, -> { where(drug: drug) }
end

app/models/batch_firm.rb
class BatchFirm < ApplicationRecord
  belongs_to :batch
  belongs_to :firm
end

app/models/drug.rb
class Drug < ApplicationRecord
  has_many :batch, dependent: :destroy
  has_many :sgtin, dependent: :destroy
  belongs_to :producer

 # validates :gtin, presence: true, uniqueness: true

  def full_name
    "#{name} #{form_name} #{form_doze} (МНН: #{mnn})"
  end
end

app/models/firm.rb
class Firm < ApplicationRecord
  has_many :sgtin

  has_many :batch_firms, dependent: :destroy
  has_many :batches, through: :batch_firms
end

app/models/gtin.rb
class Gtin < ApplicationRecord
end

app/models/producer.rb
class Producer < ApplicationRecord
  has_many :drug, dependent: :destroy
end

app/models/sgtin.rb
class Sgtin < ApplicationRecord
  belongs_to :drug
  belongs_to :batch
  belongs_to :firm

  def formatted_status_date
    status_date.strftime('%d.%m.%Y')
  end

  def formatted_last_operation_date
    last_operation_date.strftime('%d.%m.%Y')
  end
end

app/models/token.rb
class Token < ApplicationRecord
  def formatted_expiration_date
    expiration_date.strftime('%d.%m.%Y')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandling
  include Pagy::Backend
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :set_drug1, only: %i[show]
  before_action :set_batch, only: %i[show]
  before_action :set_firm, only: %i[show]

  def show
    @pagy, @sgtins = pagy Sgtin.where(batch: @batch)
    @sgtins_all = Sgtin.where(batch: @batch)
    @firms = Firm.all

    respond_to do |format|
      format.html {}

      format.zip {respond_with_zip_sgtins}
    end
  end
end

private

def set_drug1
  @drug = Drug.find(params[:drug_id])
end

def set_batch
  @batch = @drug.batch.find(params[:id])
end

def set_firm
  return @firm = Firm.find(params[:firm_id]) if params[:firm_id].present?
  @firm = Firm.first
end

def respond_with_zip_sgtins
  compressed_filestream = Zip::OutputStream.write_buffer do |zos|
    zos.put_next_entry "#{@batch.number}.xlsx"

    zos.print render_to_string(
      layout: false, handlers: [:axlsx], formats: [:xlsx],
      template: 'batches/batch', locals: {firms: @firms, sgtins: @sgtins}
    )
  end

  compressed_filestream.rewind

  send_data compressed_filestream.read, filename: "#{@drug.name[0..30]}.zip"
end

app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :set_drug, only: %i[show]

  def index
    @firms = Firm.all
    @pagy, @drugs = pagy Drug.all.order(:name)
  end

  def show
    @firms = Firm.all
    @sgtins = @drug.sgtin.all
    @batches = @drug.batch.all.order(:number)
  end
end


private

def set_drug
  @drug = Drug.find(params[:id])
end

app/controllers/sgtins_controller.rb
class SgtinsController < ApplicationController
  def destroy
    # render plain: params
    @sgtin = Sgtin.find(params[:id])
    @batch = @sgtin.batch

    @sgtins = Sgtin.where(batch: @batch, firm: @sgtin.firm).map.with_index{ |e, i| i if e.number ==@sgtin.number }.compact

    #  @sgtin.destroy

     render plain: @sgtins
    #redirect_to drug_batch_path(@batch.drug, @batch)
  end

  def create

    batch = Batch.find(params[:batch])
    firm = Firm.find(params[:firm])
    gtin = batch.drug.gtin

    SgtinImportJob.perform_later(gtin, batch, firm)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  def full_title(page_title = "")
    base_title = "Packs"

    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end

  def pagination(obj)
    raw(pagy_bootstrap_nav(obj)) if obj.pages > 1
  end
end

app/helpers/batches_helper.rb
module BatchesHelper
  def sgtins_at_firm(sgtins, firm)
    sgtins.select{ |sgtin| sgtin.firm == firm }
  end
end

app/helpers/drugs_helper.rb
module DrugsHelper
  def quantity_at_firm(drug, firm)
    drug.sgtin.where(firm: firm.id).count
  end

  def quantity_at_firm_by_bathes(drug, firm, batch)
    drug.sgtin.where(firm: firm.id, batch: batch.id).count
  end

  def quantity_at_firm_by_batches_mdlp(firm, batch)
    batches = batch.batch_firms.find_by(batch: batch, firm: firm)
    batches ? batches.quantity : 0
    end
end

app/helpers/sgtins_helper.rb
module SgtinsHelper
end

app/views/batches/show.html.erb
<%= provide :page_title, 'SGTINs'%>

<h4><%= link_to @batch.drug.full_name, drug_path(@batch.drug) %></h4>
<h6><%= @batch.drug.producer.name %></h6>
<h5>Серия: <%= @batch.number %></h5>
<h6>Годен до: <%= @batch.formatted_expiration_date %></h6>

<div class="btn-gtoup mb-3">
  <%= link_to 'Скачать в формате xlsx', drug_batch_path(format: :zip),
    class: 'btn btn-secondary btn-sm' %>
   <%= link_to 'Удалить все sgtin', drug_batch_path(),
    class: 'btn btn-danger btn-sm' %>
</div>

<ul class="nav mb-2">
  <% @firms.each do |firm| %>
    <li><%= link_to firm.name, drug_batch_path(firm_id: firm), class: 'nav-link px-2' %></li>
  <% end %>
</ul>
</nav>

<h4><%= @firm.name %></h4>

<%= pagination @pagy %>

<table class = "table table-bordered border-primary table-sm table-hover">
  <thead>
    <tr>
      <th scope="col">sgtin</td>
      <th scope="col">Статус</td>
      <th scope="col">Дата статуса</td>
      <th scope="col">Дата последней операции</td>
      <th scope="col"></td>
    </tr>
  </thead>
  <tbody>
    <% sgtins_at_firm(@sgtins, @firm).each_with_index do |sgtin, index| %>
         <tr id="sgtin-<%= index %>">
          <td><%= sgtin.number %></td>
          <td><%= sgtin.status %></td>
          <td><%= sgtin.formatted_status_date %></td>
          <td><%= sgtin.formatted_last_operation_date %></td>
          <td><%= link_to 'Удалить', sgtin_path(sgtin), data: {method: :delete} %></td>
          </tr>
    <% end %>
  </tbody>
</table>

<%= pagination @pagy %>

<%= link_to 'Назад', drug_path(@batch.drug)%>

app/views/drugs/index.html.erb
<%= provide :page_title, 'Список препаратов'%>

<h1>Препараты</h1>

<%= pagination @pagy %>

<table class = "table table-bordered border-primary table-sm table-hover">
  <thead>
    <tr class="text-center align-text-top">
      <th scope="col">Препарат</td>
      <th scope="col">Производитель</td>
      <th scope="col">GTIN</td>
      <th scope="col">Общее количество</td>

      <% @firms.each do |firm| %>
        <th scope="col" class= 'text-center'><%= firm.name %></td>
      <% end %>
     </tr>
  </thead>
  <tbody>
    <% @drugs.each do |drug| %>
        <tr class = "<%= drug.is_narcotic || drug.is_pku ? 'table-danger' : nil %>">
          <td> <%= link_to drug.full_name, drug %></td>
          <td> <%= drug.producer.name %></td>
          <td> <%= drug.gtin %></td>
          <td class="text-end"> <%= drug.sgtin.count %> / <%= BatchFirm.where(batch: Batch.where(drug: drug)).sum(&:quantity) %></td>

          <% @firms.each do |firm| %>
            <td class="text-end"> <%= quantity_at_firm(drug, firm) %> / <%= BatchFirm.where(batch: Batch.where(drug: drug), firm: firm).sum(&:quantity) %></td>
          <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

<%= pagination @pagy %>

app/views/drugs/show.html.erb
<%= provide :page_title, 'Серии'%>

<h4><%= @drug.full_name %></h4>
<h6><%= @drug.producer.name %></h6>

<table class = "table table-bordered border-primary table-sm table-hover">
  <thead>
    <tr>
      <th scope="col">Серия</td>
      <th scope="col">Срок годности</td>
      <th scope="col">Общее количество</td>

      <% @firms.each do |firm| %>
        <th scope="col"><%= firm.name %></td>
      <% end %>

    </tr>
  </thead>
  <tbody>
    <% @batches.each do |batch| %>
        <tr class = "<%= batch.expiration_date <= Time.now ? 'table-warning' : nil %>">
          <td><%= link_to batch.number, drug_batch_path(@drug, batch) %></td>
          <td><%= batch.formatted_expiration_date %></td>
          <td><%= batch.sgtin.count %> / <%= BatchFirm.where(batch: batch).sum(&:quantity) %></td>

          <% @firms.each do |firm| %>
            <td> <%= "#{quantity_at_firm_by_bathes(batch.drug, firm, batch)}
                     / #{quantity_at_firm_by_batches_mdlp(firm, batch)}"
                 %>
                 <%= link_to 'Загрузить', sgtins_path(batch: batch, firm: firm), method: :post %>
            </td>
          <% end %>
        </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Назад', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <header class="p-3 bg-dark text-white">
      <div class="container">
        <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <ul class=" nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><%= link_to 'Главная', root_path, class: 'nav-link px-2 text-white' %></li>
          </ul>
        </nav>
      </div>
    </header>

    <main class="container mt-3">
        <%= yield %>
    </main>
  </body>
</html>